export const FETCH_ROBOTS_START: string = 'FETCH_ROBOTS_START';
export const FETCH_ROBOTS_SUCCESS: string = 'FETCH_ROBOTS_SUCCESS';
export const FETCH_ROBOTS_FAILED: string = 'FETCH_ROBOTS_FAIL';
export const FILTER_ROBOTS_ONCHANGE: string = 'FILTER_ROBOTS_ONCHANGE';
