export const FETCH_ROBOTS_START = 'FETCH_ROBOTS_START';
export const FETCH_ROBOTS_SUCCESS = 'FETCH_ROBOTS_SUCCESS';
export const FETCH_ROBOTS_FAILED = 'FETCH_ROBOTS_FAIL';
export const FILTER_ROBOTS_ONCHANGE = 'FILTER_ROBOTS_ONCHANGE';
