version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1    
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build

workflows:
  version: 2
  build:
    jobs:
      - build